import mongoose from 'mongoose';
import { orderItemSchema } from './OrderItem.js';
import { addressSchema } from './Address.js';
import {
  ORDER_STATUS,
  ORDER_STATUS_VALUES,
  PAYMENT_METHOD_VALUES,
  PAYMENT_STATUS,
  PAYMENT_STATUS_VALUES,
} from '../utils/constants.js';

const pricingSchema = new mongoose.Schema(
  {
    /** Sum of list prices x quantity, before product discounts. */
    listSubtotal: { type: Number, required: true, min: 0 },
    /** Sum of charged unit prices x quantity. */
    subtotal: { type: Number, required: true, min: 0 },
    /** listSubtotal - subtotal (savings already baked into product pricing). */
    itemDiscount: { type: Number, default: 0, min: 0 },
    couponDiscount: { type: Number, default: 0, min: 0 },
    deliveryCharge: { type: Number, default: 0, min: 0 },
    taxRate: { type: Number, default: 0, min: 0 },
    taxAmount: { type: Number, default: 0, min: 0 },
    total: { type: Number, required: true, min: 0 },
  },
  { _id: false }
);

const timelineEntrySchema = new mongoose.Schema(
  {
    status: { type: String, enum: ORDER_STATUS_VALUES, required: true },
    note: { type: String, maxlength: 400 },
    at: { type: Date, default: Date.now },
    by: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    byName: String,
  },
  { _id: false }
);

const orderSchema = new mongoose.Schema(
  {
    /** Human-readable, e.g. ACH-2026-000123. Generated by orderNumberService. */
    orderNumber: { type: String, required: true, unique: true },

    user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null, index: true },
    isGuest: { type: Boolean, default: false },

    /** Contact details captured at checkout (may differ from the account). */
    customer: {
      name: { type: String, required: true, trim: true },
      email: { type: String, required: true, lowercase: true, trim: true },
      phone: { type: String, required: true, trim: true },
    },

    items: {
      type: [orderItemSchema],
      validate: { validator: (v) => v.length > 0, message: 'An order needs at least one item' },
    },

    shippingAddress: { type: addressSchema, required: true },
    pricing: { type: pricingSchema, required: true },

    coupon: {
      code: String,
      couponId: { type: mongoose.Schema.Types.ObjectId, ref: 'Coupon' },
      discountType: String,
      discountValue: Number,
    },

    delivery: {
      zoneId: { type: mongoose.Schema.Types.ObjectId, ref: 'DeliveryZone' },
      zoneName: String,
      estimatedDaysMin: Number,
      estimatedDaysMax: Number,
      estimatedDeliveryDate: Date,
      trackingNumber: String,
      courier: String,
    },

    paymentMethod: { type: String, enum: PAYMENT_METHOD_VALUES, required: true },
    paymentStatus: {
      type: String,
      enum: PAYMENT_STATUS_VALUES,
      default: PAYMENT_STATUS.PENDING,
      index: true,
    },
    payment: { type: mongoose.Schema.Types.ObjectId, ref: 'Payment', default: null },

    status: {
      type: String,
      enum: ORDER_STATUS_VALUES,
      default: ORDER_STATUS.PENDING,
      index: true,
    },
    timeline: { type: [timelineEntrySchema], default: [] },

    /**
     * Tracks what has happened to inventory for this order, which makes every
     * stock transition idempotent: a duplicate payment callback cannot deduct
     * stock twice, and cancelling twice cannot release it twice.
     */
    stockState: {
      type: String,
      enum: ['reserved', 'committed', 'released', 'restocked'],
      default: 'reserved',
      index: true,
    },

    customerNote: { type: String, maxlength: 500 },
    adminNote: { type: String, maxlength: 1000 },

    paidAt: Date,
    packedAt: Date,
    shippedAt: Date,
    deliveredAt: Date,
    cancelledAt: Date,
    cancelReason: { type: String, maxlength: 400 },
    refundedAt: Date,
    refundAmount: { type: Number, default: 0 },
    /** Set when the reservation window lapses so the cleanup job skips it. */
    reservationExpiresAt: { type: Date, index: true },
  },
  { timestamps: true, toJSON: { virtuals: true }, toObject: { virtuals: true } }
);

orderSchema.index({ createdAt: -1 });
orderSchema.index({ 'customer.phone': 1, orderNumber: 1 });
orderSchema.index({ 'customer.email': 1, createdAt: -1 });
orderSchema.index({ status: 1, createdAt: -1 });
orderSchema.index({ user: 1, createdAt: -1 });

orderSchema.virtual('itemCount').get(function itemCount() {
  return (this.items ?? []).reduce((sum, item) => sum + item.quantity, 0);
});

orderSchema.virtual('isPaid').get(function isPaid() {
  return this.paymentStatus === PAYMENT_STATUS.PAID;
});

orderSchema.virtual('isCancellable').get(function isCancellable() {
  return [ORDER_STATUS.PENDING, ORDER_STATUS.PAYMENT_PENDING, ORDER_STATUS.PAID].includes(
    this.status
  );
});

orderSchema.methods.pushTimeline = function pushTimeline(status, note, actor) {
  this.timeline.push({
    status,
    note,
    at: new Date(),
    by: actor?._id,
    byName: actor?.name,
  });
  return this;
};

export default mongoose.models.Order || mongoose.model('Order', orderSchema);
